# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Study Progress
email: eitzo@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site's purpose is to inform people about my studies.

# Build settings
markdown: kramdown
